import { ReactComponent as ClockIcon } from "./static/images/clock.svg";
import { ReactComponent as FolderIcon } from "./static/images/folder.svg";
import { ReactComponent as SearchIcon } from "./static/images/search.svg";

import "./scss/style.scss";

export { Populate } from "./Defaults";
export * from "./Archive";
export * from "./Category";
export * from "./Context";
export * from "./elements/ArchiveCard";
export * from "./elements/ArchiveRender";
export * from "./elements/ErrorRouting";
export * from "./elements/Loading";
export * from "./elements/LoadingError";
export * from "./elements/NoSearchResults";
export * from "./elements/NotFound";
export * from "./elements/PageWidth";
export * from "./elements/Pagination";
export * from "./elements/Permissions";
export * from "./elements/PostContent";
export * from "./elements/SearchForm";
export * from "./elements/Seo";
export * from "./elements/SingleRender";
export * from "./elements/SingleTitle";
export * from "./elements/Title";
export * from "./gql/fragments";
export * from "./gql/queries";
export * from "./hooks/useArchive";
export * from "./hooks/useCategory";
export * from "./hooks/useHeartbeat";
export * from "./hooks/usePagination";
export * from "./hooks/useSearch";
export * from "./hooks/useSingle";
export * from "./Preview";
export * from "./Provider";
export * from "./Search";
export * from "./Single";

export { ClockIcon, FolderIcon, SearchIcon };
